	SET IDENTITY_INSERT [dbo].[Culture] ON 

	INSERT INTO [dbo].[Culture]([Id],[Name],[EnglishName],[NativeName])
    VALUES 
    (1,N'aa-DJ',N'Afar (Djibouti)',N'Qafar (Yabuuti)'),
	(2,N'aa-ER',N'Afar (Eritrea)',N'Qafar (Eretria)'),
	(3,N'aa-ET',N'Afar (Ethiopia)',N'Qafar (Otobbia)'),
	(4,N'af-NA',N'Afrikaans (Namibia)',N'Afrikaans (Namibië)'),
	(5,N'af-ZA',N'Afrikaans (South Africa)',N'Afrikaans (Suid-Afrika)'),
	(6,N'agq-CM',N'Aghem (Cameroon)',N'Aghem (Kàmàlûŋ)'),
	(7,N'ak-GH',N'Akan (Ghana)',N'Akan (Gaana)'),
	(8,N'am-ET',N'Amharic (Ethiopia)',N'አማርኛ (ኢትዮጵያ)'),
	(9,N'ar-001',N'Arabic (World)',N'العربية (العالم)'),
	(10,N'ar-AE',N'Arabic (United Arab Emirates)',N'العربية (الإمارات العربية المتحدة)'),
	(11,N'ar-BH',N'Arabic (Bahrain)',N'العربية (البحرين)'),
	(12,N'ar-DJ',N'Arabic (Djibouti)',N'العربية (جيبوتي)'),
	(13,N'ar-DZ',N'Arabic (Algeria)',N'العربية (الجزائر)'),
	(14,N'ar-EG',N'Arabic (Egypt)',N'العربية (مصر)'),
	(15,N'ar-ER',N'Arabic (Eritrea)',N'العربية (إريتريا)'),
	(16,N'ar-IL',N'Arabic (Israel)',N'العربية (إسرائيل)'),
	(17,N'ar-IQ',N'Arabic (Iraq)',N'العربية (العراق)'),
	(18,N'ar-JO',N'Arabic (Jordan)',N'العربية (الأردن)'),
	(19,N'ar-KM',N'Arabic (Comoros)',N'العربية (جزر القمر)'),
	(20,N'ar-KW',N'Arabic (Kuwait)',N'العربية (الكويت)'),
	(21,N'ar-LB',N'Arabic (Lebanon)',N'العربية (لبنان)'),
	(22,N'ar-LY',N'Arabic (Libya)',N'العربية (ليبيا)'),
	(23,N'ar-MA',N'Arabic (Morocco)',N'العربية (المملكة المغربية)'),
	(24,N'ar-MR',N'Arabic (Mauritania)',N'العربية (موريتانيا)'),
	(25,N'ar-OM',N'Arabic (Oman)',N'العربية (عمان)'),
	(26,N'ar-PS',N'Arabic (Palestinian Authority)',N'العربية (السلطة الفلسطينية)'),
	(27,N'ar-QA',N'Arabic (Qatar)',N'العربية (قطر)'),
	(28,N'ar-SA',N'Arabic (Saudi Arabia)',N'العربية (المملكة العربية السعودية)'),
	(29,N'ar-SD',N'Arabic (Sudan)',N'العربية (السودان)'),
	(30,N'ar-SO',N'Arabic (Somalia)',N'العربية (الصومال)'),
	(31,N'ar-SS',N'Arabic (South Sudan)',N'العربية (جنوب السودان)'),
	(32,N'ar-SY',N'Arabic (Syria)',N'العربية (سوريا)'),
	(33,N'ar-TD',N'Arabic (Chad)',N'العربية (تشاد)'),
	(34,N'ar-TN',N'Arabic (Tunisia)',N'العربية (تونس)'),
	(35,N'ar-YE',N'Arabic (Yemen)',N'العربية (اليمن)'),
	(36,N'arn-CL',N'Mapudungun (Chile)',N'Mapudungun (Chile)'),
	(37,N'as-IN',N'Assamese (India)',N'অসমীয়া (ভাৰত)'),
	(38,N'asa-TZ',N'Asu (Tanzania)',N'Kipare (Tadhania)'),
	(39,N'ast-ES',N'Asturian (Spain)',N'asturianu (España)'),
	(40,N'az-Cyrl-AZ',N'Azerbaijani (Cyrillic, Azerbaijan)',N'азәрбајҹан (Азәрбајҹан)'),
	(41,N'az-Latn-AZ',N'Azerbaijani (Latin, Azerbaijan)',N'azərbaycan (Azərbaycan)'),
	(42,N'ba-RU',N'Bashkir (Russia)',N'Башҡорт (Рәсәй)'),
	(43,N'bas-CM',N'Basaa (Cameroon)',N'Ɓàsàa (Kàmɛ̀rûn)'),
	(44,N'be-BY',N'Belarusian (Belarus)',N'Беларуская (Беларусь)'),
	(45,N'bem-ZM',N'Bemba (Zambia)',N'Ichibemba (Zambia)'),
	(46,N'bez-TZ',N'Bena (Tanzania)',N'Hibena (Hutanzania)'),
	(47,N'bg-BG',N'Bulgarian (Bulgaria)',N'български (България)'),
	(48,N'bin-NG',N'Edo (Nigeria)',N'Ẹ̀dó (Nigeria)'),
	(49,N'bm-Latn-ML',N'Bamanankan (Latin, Mali)',N'bamanakan (Mali)'),
	(50,N'bn-BD',N'Bangla (Bangladesh)',N'বাংলা (বাংলাদেশ)'),
	(51,N'bn-IN',N'Bangla (India)',N'বাংলা (ভারত)'),
	(52,N'bo-CN',N'Tibetan (China)',N'བོད་ཡིག (ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ།)'),
	(53,N'bo-IN',N'Tibetan (India)',N'བོད་སྐད་ (རྒྱ་གར་)'),
	(54,N'br-FR',N'Breton (France)',N'brezhoneg (Frañs)'),
	(55,N'brx-IN',N'Bodo (India)',N'बड़ो (भारत)'),
	(56,N'bs-Cyrl-BA',N'Bosnian (Cyrillic, Bosnia and Herzegovina)',N'босански (Босна и Херцеговина)'),
	(57,N'bs-Latn-BA',N'Bosnian (Latin, Bosnia and Herzegovina)',N'bosanski (Bosna i Hercegovina)'),
	(58,N'byn-ER',N'Blin (Eritrea)',N'ብሊን (ኤርትራ)'),
	(59,N'ca-AD',N'Catalan (Andorra)',N'català (Andorra)'),
	(60,N'ca-ES',N'Catalan (Catalan)',N'català (català)'),
	(61,N'ca-ES-valencia',N'Valencian (Spain)',N'valencià (Espanya)'),
	(62,N'ca-FR',N'Catalan (France)',N'català (França)'),
	(63,N'ca-IT',N'Catalan (Italy)',N'català (Itàlia)'),
	(64,N'ce-RU',N'Chechen (Russia)',N'нохчийн (Росси)'),
	(65,N'cgg-UG',N'Chiga (Uganda)',N'Rukiga (Uganda)'),
	(66,N'chr-Cher-US',N'Cherokee (Cherokee, United States)',N'ᏣᎳᎩ (ᏌᏊ ᎢᏳᎾᎵᏍᏔᏅ ᏍᎦᏚᎩ)'),
	(67,N'co-FR',N'Corsican (France)',N'Corsu (Francia)'),
	(68,N'cs-CZ',N'Czech (Czechia)',N'čeština (Česko)'),
	(69,N'cu-RU',N'Church Slavic (Russia)',N'церковнослове́нскїй (рѡссі́а)'),
	(70,N'cy-GB',N'Welsh (United Kingdom)',N'Cymraeg (Y Deyrnas Unedig)'),
	(71,N'da-DK',N'Danish (Denmark)',N'dansk (Danmark)'),
	(72,N'da-GL',N'Danish (Greenland)',N'dansk (Grønland)'),
	(73,N'dav-KE',N'Taita (Kenya)',N'Kitaita (Kenya)'),
	(74,N'de-AT',N'German (Austria)',N'Deutsch (Österreich)'),
	(75,N'de-BE',N'German (Belgium)',N'Deutsch (Belgien)'),
	(76,N'de-CH',N'German (Switzerland)',N'Deutsch (Schweiz)'),
	(77,N'de-DE',N'German (Germany)',N'Deutsch (Deutschland)'),
	(78,N'de-IT',N'German (Italy)',N'Deutsch (Italien)'),
	(79,N'de-LI',N'German (Liechtenstein)',N'Deutsch (Liechtenstein)'),
	(80,N'de-LU',N'German (Luxembourg)',N'Deutsch (Luxemburg)'),
	(81,N'dje-NE',N'Zarma (Niger)',N'Zarmaciine (Nižer)'),
	(82,N'dsb-DE',N'Lower Sorbian (Germany)',N'dolnoserbšćina (Nimska)'),
	(83,N'dua-CM',N'Duala (Cameroon)',N'duálá (Cameroun)'),
	(84,N'dv-MV',N'Divehi (Maldives)',N'ދިވެހިބަސް (ދިވެހި ރާއްޖެ)'),
	(85,N'dyo-SN',N'Jola-Fonyi (Senegal)',N'joola (Senegal)'),
	(86,N'dz-BT',N'Dzongkha (Bhutan)',N'རྫོང་ཁ (འབྲུག)'),
	(87,N'ebu-KE',N'Embu (Kenya)',N'Kĩembu (Kenya)'),
	(88,N'ee-GH',N'Ewe (Ghana)',N'Eʋegbe (Ghana nutome)'),
	(89,N'ee-TG',N'Ewe (Togo)',N'Eʋegbe (Togo nutome)'),
	(90,N'el-CY',N'Greek (Cyprus)',N'Ελληνικά (Κύπρος)'),
	(91,N'el-GR',N'Greek (Greece)',N'Ελληνικά (Ελλάδα)'),
	(92,N'en-001',N'English (World)',N'English (World)'),
	(93,N'en-029',N'English (Caribbean)',N'English (Caribbean)'),
	(94,N'en-150',N'English (Europe)',N'English (Europe)'),
	(95,N'en-AG',N'English (Antigua and Barbuda)',N'English (Antigua and Barbuda)'),
	(96,N'en-AI',N'English (Anguilla)',N'English (Anguilla)'),
	(97,N'en-AS',N'English (American Samoa)',N'English (American Samoa)'),
	(98,N'en-AT',N'English (Austria)',N'English (Austria)'),
	(99,N'en-AU',N'English (Australia)',N'English (Australia)'),
	(100,N'en-BB',N'English (Barbados)',N'English (Barbados)'),
	(101,N'en-BE',N'English (Belgium)',N'English (Belgium)'),
	(102,N'en-BI',N'English (Burundi)',N'English (Burundi)'),
	(103,N'en-BM',N'English (Bermuda)',N'English (Bermuda)'),
	(104,N'en-BS',N'English (Bahamas)',N'English (Bahamas)'),
	(105,N'en-BW',N'English (Botswana)',N'English (Botswana)'),
	(106,N'en-BZ',N'English (Belize)',N'English (Belize)'),
	(107,N'en-CA',N'English (Canada)',N'English (Canada)'),
	(108,N'en-CC',N'English (Cocos (Keeling) Islands)',N'English (Cocos (Keeling) Islands)'),
	(109,N'en-CH',N'English (Switzerland)',N'English (Switzerland)'),
	(110,N'en-CK',N'English (Cook Islands)',N'English (Cook Islands)'),
	(111,N'en-CM',N'English (Cameroon)',N'English (Cameroon)'),
	(112,N'en-CX',N'English (Christmas Island)',N'English (Christmas Island)'),
	(113,N'en-CY',N'English (Cyprus)',N'English (Cyprus)'),
	(114,N'en-DE',N'English (Germany)',N'English (Germany)'),
	(115,N'en-DK',N'English (Denmark)',N'English (Denmark)'),
	(116,N'en-DM',N'English (Dominica)',N'English (Dominica)'),
	(117,N'en-ER',N'English (Eritrea)',N'English (Eritrea)'),
	(118,N'en-FI',N'English (Finland)',N'English (Finland)'),
	(119,N'en-FJ',N'English (Fiji)',N'English (Fiji)'),
	(120,N'en-FK',N'English (Falkland Islands)',N'English (Falkland Islands)'),
	(121,N'en-FM',N'English (Micronesia)',N'English (Micronesia)'),
	(122,N'en-GB',N'English (United Kingdom)',N'English (United Kingdom)'),
	(123,N'en-GD',N'English (Grenada)',N'English (Grenada)'),
	(124,N'en-GG',N'English (Guernsey)',N'English (Guernsey)'),
	(125,N'en-GH',N'English (Ghana)',N'English (Ghana)'),
	(126,N'en-GI',N'English (Gibraltar)',N'English (Gibraltar)'),
	(127,N'en-GM',N'English (Gambia)',N'English (Gambia)'),
	(128,N'en-GU',N'English (Guam)',N'English (Guam)'),
	(129,N'en-GY',N'English (Guyana)',N'English (Guyana)'),
	(130,N'en-HK',N'English (Hong Kong SAR)',N'English (Hong Kong SAR)'),
	(131,N'en-ID',N'English (Indonesia)',N'English (Indonesia)'),
	(132,N'en-IE',N'English (Ireland)',N'English (Ireland)'),
	(133,N'en-IL',N'English (Israel)',N'English (Israel)'),
	(134,N'en-IM',N'English (Isle of Man)',N'English (Isle of Man)'),
	(135,N'en-IN',N'English (India)',N'English (India)'),
	(136,N'en-IO',N'English (British Indian Ocean Territory)',N'English (British Indian Ocean Territory)'),
	(137,N'en-JE',N'English (Jersey)',N'English (Jersey)'),
	(138,N'en-JM',N'English (Jamaica)',N'English (Jamaica)'),
	(139,N'en-KE',N'English (Kenya)',N'English (Kenya)'),
	(140,N'en-KI',N'English (Kiribati)',N'English (Kiribati)'),
	(141,N'en-KN',N'English (Saint Kitts and Nevis)',N'English (Saint Kitts and Nevis)'),
	(142,N'en-KY',N'English (Cayman Islands)',N'English (Cayman Islands)'),
	(143,N'en-LC',N'English (Saint Lucia)',N'English (Saint Lucia)'),
	(144,N'en-LR',N'English (Liberia)',N'English (Liberia)'),
	(145,N'en-LS',N'English (Lesotho)',N'English (Lesotho)'),
	(146,N'en-MG',N'English (Madagascar)',N'English (Madagascar)'),
	(147,N'en-MH',N'English (Marshall Islands)',N'English (Marshall Islands)'),
	(148,N'en-MO',N'English (Macao SAR)',N'English (Macao SAR)'),
	(149,N'en-MP',N'English (Northern Mariana Islands)',N'English (Northern Mariana Islands)'),
	(150,N'en-MS',N'English (Montserrat)',N'English (Montserrat)'),
	(151,N'en-MT',N'English (Malta)',N'English (Malta)'),
	(152,N'en-MU',N'English (Mauritius)',N'English (Mauritius)'),
	(153,N'en-MW',N'English (Malawi)',N'English (Malawi)'),
	(154,N'en-MY',N'English (Malaysia)',N'English (Malaysia)'),
	(155,N'en-NA',N'English (Namibia)',N'English (Namibia)'),
	(156,N'en-NF',N'English (Norfolk Island)',N'English (Norfolk Island)'),
	(157,N'en-NG',N'English (Nigeria)',N'English (Nigeria)'),
	(158,N'en-NL',N'English (Netherlands)',N'English (Netherlands)'),
	(159,N'en-NR',N'English (Nauru)',N'English (Nauru)'),
	(160,N'en-NU',N'English (Niue)',N'English (Niue)'),
	(161,N'en-NZ',N'English (New Zealand)',N'English (New Zealand)'),
	(162,N'en-PG',N'English (Papua New Guinea)',N'English (Papua New Guinea)'),
	(163,N'en-PH',N'English (Philippines)',N'English (Philippines)'),
	(164,N'en-PK',N'English (Pakistan)',N'English (Pakistan)'),
	(165,N'en-PN',N'English (Pitcairn Islands)',N'English (Pitcairn Islands)'),
	(166,N'en-PR',N'English (Puerto Rico)',N'English (Puerto Rico)'),
	(167,N'en-PW',N'English (Palau)',N'English (Palau)'),
	(168,N'en-RW',N'English (Rwanda)',N'English (Rwanda)'),
	(169,N'en-SB',N'English (Solomon Islands)',N'English (Solomon Islands)'),
	(170,N'en-SC',N'English (Seychelles)',N'English (Seychelles)'),
	(171,N'en-SD',N'English (Sudan)',N'English (Sudan)'),
	(172,N'en-SE',N'English (Sweden)',N'English (Sweden)'),
	(173,N'en-SG',N'English (Singapore)',N'English (Singapore)'),
	(174,N'en-SH',N'English (St Helena, Ascension, Tristan da Cunha)',N'English (St Helena, Ascension, Tristan da Cunha)'),
	(175,N'en-SI',N'English (Slovenia)',N'English (Slovenia)'),
	(176,N'en-SL',N'English (Sierra Leone)',N'English (Sierra Leone)'),
	(177,N'en-SS',N'English (South Sudan)',N'English (South Sudan)'),
	(178,N'en-SX',N'English (Sint Maarten)',N'English (Sint Maarten)'),
	(179,N'en-SZ',N'English (Swaziland)',N'English (Swaziland)'),
	(180,N'en-TC',N'English (Turks and Caicos Islands)',N'English (Turks and Caicos Islands)'),
	(181,N'en-TK',N'English (Tokelau)',N'English (Tokelau)'),
	(182,N'en-TO',N'English (Tonga)',N'English (Tonga)'),
	(183,N'en-TT',N'English (Trinidad and Tobago)',N'English (Trinidad and Tobago)'),
	(184,N'en-TV',N'English (Tuvalu)',N'English (Tuvalu)'),
	(185,N'en-TZ',N'English (Tanzania)',N'English (Tanzania)'),
	(186,N'en-UG',N'English (Uganda)',N'English (Uganda)'),
	(187,N'en-UM',N'English (U.S. Outlying Islands)',N'English (U.S. Outlying Islands)'),
	(188,N'en-US',N'English (United States)',N'English (United States)'),
	(189,N'en-VC',N'English (Saint Vincent and the Grenadines)',N'English (Saint Vincent and the Grenadines)'),
	(190,N'en-VG',N'English (British Virgin Islands)',N'English (British Virgin Islands)'),
	(191,N'en-VI',N'English (U.S. Virgin Islands)',N'English (U.S. Virgin Islands)'),
	(192,N'en-VU',N'English (Vanuatu)',N'English (Vanuatu)'),
	(193,N'en-WS',N'English (Samoa)',N'English (Samoa)'),
	(194,N'en-ZA',N'English (South Africa)',N'English (South Africa)'),
	(195,N'en-ZM',N'English (Zambia)',N'English (Zambia)'),
	(196,N'en-ZW',N'English (Zimbabwe)',N'English (Zimbabwe)'),
	(197,N'eo-001',N'Esperanto (World)',N'esperanto (World)'),
	(198,N'es-419',N'Spanish (Latin America)',N'español (Latinoamérica)'),
	(199,N'es-AR',N'Spanish (Argentina)',N'español (Argentina)'),
	(200,N'es-BO',N'Spanish (Bolivia)',N'español (Bolivia)'),
	(201,N'es-BR',N'Spanish (Brazil)',N'español (Brasil)'),
	(202,N'es-BZ',N'Spanish (Belize)',N'español (Belice)'),
	(203,N'es-CL',N'Spanish (Chile)',N'español (Chile)'),
	(204,N'es-CO',N'Spanish (Colombia)',N'español (Colombia)'),
	(205,N'es-CR',N'Spanish (Costa Rica)',N'español (Costa Rica)'),
	(206,N'es-CU',N'Spanish (Cuba)',N'español (Cuba)'),
	(207,N'es-DO',N'Spanish (Dominican Republic)',N'español (República Dominicana)'),
	(208,N'es-EC',N'Spanish (Ecuador)',N'español (Ecuador)'),
	(209,N'es-ES',N'Spanish (Spain, International Sort)',N'español (España, alfabetización internacional)'),
	(210,N'es-GQ',N'Spanish (Equatorial Guinea)',N'español (Guinea Ecuatorial)'),
	(211,N'es-GT',N'Spanish (Guatemala)',N'español (Guatemala)'),
	(212,N'es-HN',N'Spanish (Honduras)',N'español (Honduras)'),
	(213,N'es-MX',N'Spanish (Mexico)',N'español (México)'),
	(214,N'es-NI',N'Spanish (Nicaragua)',N'español (Nicaragua)'),
	(215,N'es-PA',N'Spanish (Panama)',N'español (Panamá)'),
	(216,N'es-PE',N'Spanish (Peru)',N'español (Perú)'),
	(217,N'es-PH',N'Spanish (Philippines)',N'español (Filipinas)'),
	(218,N'es-PR',N'Spanish (Puerto Rico)',N'español (Puerto Rico)'),
	(219,N'es-PY',N'Spanish (Paraguay)',N'español (Paraguay)'),
	(220,N'es-SV',N'Spanish (El Salvador)',N'español (El Salvador)'),
	(221,N'es-US',N'Spanish (United States)',N'español (Estados Unidos)'),
	(222,N'es-UY',N'Spanish (Uruguay)',N'español (Uruguay)'),
	(223,N'es-VE',N'Spanish (Venezuela)',N'español (Venezuela)'),
	(224,N'et-EE',N'Estonian (Estonia)',N'eesti (Eesti)'),
	(225,N'eu-ES',N'Basque (Basque)',N'euskara (euskara)'),
	(226,N'ewo-CM',N'Ewondo (Cameroon)',N'ewondo (Kamərún)'),
	(227,N'fa-IR',N'Persian (Iran)',N'فارسی (ایران)'),
	(228,N'ff-CM',N'Fulah (Cameroon)',N'Pulaar (Kameruun)'),
	(229,N'ff-GN',N'Fulah (Guinea)',N'Pulaar (Gine)'),
	(230,N'ff-Latn-SN',N'Fulah (Latin, Senegal)',N'Fulah (Sénégal)'),
	(231,N'ff-MR',N'Fulah (Mauritania)',N'Pulaar (Muritani)'),
	(232,N'ff-NG',N'Fulah (Nigeria)',N'Pulaar (Nigeria)'),
	(233,N'fi-FI',N'Finnish (Finland)',N'suomi (Suomi)'),
	(234,N'fil-PH',N'Filipino (Philippines)',N'Filipino (Pilipinas)'),
	(235,N'fo-DK',N'Faroese (Denmark)',N'føroyskt (Danmark)'),
	(236,N'fo-FO',N'Faroese (Faroe Islands)',N'føroyskt (Føroyar)'),
	(237,N'fr-029',N'French (Caribbean)',N'français (caraïbes)'),
	(238,N'fr-BE',N'French (Belgium)',N'français (Belgique)'),
	(239,N'fr-BF',N'French (Burkina Faso)',N'français (Burkina Faso)'),
	(240,N'fr-BI',N'French (Burundi)',N'français (Burundi)'),
	(241,N'fr-BJ',N'French (Benin)',N'français (Bénin)'),
	(242,N'fr-BL',N'French (Saint Barthélemy)',N'français (Saint-Barthélemy)'),
	(243,N'fr-CA',N'French (Canada)',N'français (Canada)'),
	(244,N'fr-CD',N'French Congo (DRC)',N'français (Congo, République démocratique du)'),
	(245,N'fr-CF',N'French (Central African Republic)',N'français (République centrafricaine)'),
	(246,N'fr-CG',N'French (Congo)',N'français (Congo)'),
	(247,N'fr-CH',N'French (Switzerland)',N'français (Suisse)'),
	(248,N'fr-CI',N'French (Côte d’Ivoire)',N'français (Côte d’Ivoire)'),
	(249,N'fr-CM',N'French (Cameroon)',N'français (Cameroun)'),
	(250,N'fr-DJ',N'French (Djibouti)',N'français (Djibouti)'),
	(251,N'fr-DZ',N'French (Algeria)',N'français (Algérie)'),
	(252,N'fr-FR',N'French (France)',N'français (France)'),
	(253,N'fr-GA',N'French (Gabon)',N'français (Gabon)'),
	(254,N'fr-GF',N'French (French Guiana)',N'français (Guyane française)'),
	(255,N'fr-GN',N'French (Guinea)',N'français (Guinée)'),
	(256,N'fr-GP',N'French (Guadeloupe)',N'français (Guadeloupe)'),
	(257,N'fr-GQ',N'French (Equatorial Guinea)',N'français (Guinée équatoriale)'),
	(258,N'fr-HT',N'French (Haiti)',N'français (Haïti)'),
	(259,N'fr-KM',N'French (Comoros)',N'français (Comores)'),
	(260,N'fr-LU',N'French (Luxembourg)',N'français (Luxembourg)'),
	(261,N'fr-MA',N'French (Morocco)',N'français (Maroc)'),
	(262,N'fr-MC',N'French (Monaco)',N'français (Monaco)'),
	(263,N'fr-MF',N'French (Saint Martin)',N'français (Saint-Martin)'),
	(264,N'fr-MG',N'French (Madagascar)',N'français (Madagascar)'),
	(265,N'fr-ML',N'French (Mali)',N'français (Mali)'),
	(266,N'fr-MQ',N'French (Martinique)',N'français (Martinique)'),
	(267,N'fr-MR',N'French (Mauritania)',N'français (Mauritanie)'),
	(268,N'fr-MU',N'French (Mauritius)',N'français (Maurice)'),
	(269,N'fr-NC',N'French (New Caledonia)',N'français (Nouvelle-Calédonie)'),
	(270,N'fr-NE',N'French (Niger)',N'français (Niger)'),
	(271,N'fr-PF',N'French (French Polynesia)',N'français (Polynésie française)'),
	(272,N'fr-PM',N'French (Saint Pierre and Miquelon)',N'français (Saint-Pierre-et-Miquelon)'),
	(273,N'fr-RE',N'French (Réunion)',N'français (La Réunion)'),
	(274,N'fr-RW',N'French (Rwanda)',N'français (Rwanda)'),
	(275,N'fr-SC',N'French (Seychelles)',N'français (Seychelles)'),
	(276,N'fr-SN',N'French (Senegal)',N'français (Sénégal)'),
	(277,N'fr-SY',N'French (Syria)',N'français (Syrie)'),
	(278,N'fr-TD',N'French (Chad)',N'français (Tchad)'),
	(279,N'fr-TG',N'French (Togo)',N'français (Togo)'),
	(280,N'fr-TN',N'French (Tunisia)',N'français (Tunisie)'),
	(281,N'fr-VU',N'French (Vanuatu)',N'français (Vanuatu)'),
	(282,N'fr-WF',N'French (Wallis and Futuna)',N'français (Wallis-et-Futuna)'),
	(283,N'fr-YT',N'French (Mayotte)',N'français (Mayotte)'),
	(284,N'fur-IT',N'Friulian (Italy)',N'furlan (Italie)'),
	(285,N'fy-NL',N'Western Frisian (Netherlands)',N'Frysk (Nederlân)'),
	(286,N'ga-IE',N'Irish (Ireland)',N'Gaeilge (Éire)'),
	(287,N'gd-GB',N'Scottish Gaelic (United Kingdom)',N'Gàidhlig (An Rìoghachd Aonaichte)'),
	(288,N'gl-ES',N'Galician (Galician)',N'galego (galego)'),
	(289,N'gn-PY',N'Guarani (Paraguay)',N'Avañe’ẽ (Paraguái)'),
	(290,N'gsw-CH',N'Swiss German (Switzerland)',N'Schwiizertüütsch (Schwiiz)'),
	(291,N'gsw-FR',N'Alsatian (France)',N'Elsässisch (Frànkrisch)'),
	(292,N'gsw-LI',N'Swiss German (Liechtenstein)',N'Schwiizertüütsch (Liächteschtäi)'),
	(293,N'gu-IN',N'Gujarati (India)',N'ગુજરાતી (ભારત)'),
	(294,N'guz-KE',N'Gusii (Kenya)',N'Ekegusii (Kenya)'),
	(295,N'gv-IM',N'Manx (Isle of Man)',N'Gaelg (Ellan Vannin)'),
	(296,N'ha-Latn-GH',N'Hausa (Latin, Ghana)',N'Hausa (Gana)'),
	(297,N'ha-Latn-NE',N'Hausa (Latin, Niger)',N'Hausa (Nijar)'),
	(298,N'ha-Latn-NG',N'Hausa (Latin, Nigeria)',N'Hausa (Najeriya)'),
	(299,N'haw-US',N'Hawaiian (United States)',N'ʻŌlelo Hawaiʻi (ʻAmelika Hui Pū ʻIa)'),
	(300,N'he-IL',N'Hebrew (Israel)',N'עברית (ישראל)'),
	(301,N'hi-IN',N'Hindi (India)',N'हिन्दी (भारत)'),
	(302,N'hr-BA',N'Croatian (Bosnia and Herzegovina)',N'hrvatski (Bosna i Hercegovina)'),
	(303,N'hr-HR',N'Croatian (Croatia)',N'hrvatski (Hrvatska)'),
	(304,N'hsb-DE',N'Upper Sorbian (Germany)',N'hornjoserbšćina (Němska)'),
	(305,N'hu-HU',N'Hungarian (Hungary)',N'magyar (Magyarország)'),
	(306,N'hy-AM',N'Armenian (Armenia)',N'Հայերեն (Հայաստան)'),
	(307,N'ia-001',N'Interlingua (World)',N'interlingua (World)'),
	(308,N'ia-FR',N'Interlingua (France)',N'interlingua (Francia)'),
	(309,N'ibb-NG',N'Ibibio (Nigeria)',N'Ibibio-Efik (Nigeria)'),
	(310,N'id-ID',N'Indonesian (Indonesia)',N'Indonesia (Indonesia)'),
	(311,N'ig-NG',N'Igbo (Nigeria)',N'Igbo (Naịjịrịa)'),
	(312,N'ii-CN',N'Yi (China)',N'ꆈꌠꁱꂷ (ꍏꉸꏓꂱꇭꉼꇩ)'),
	(313,N'is-IS',N'Icelandic (Iceland)',N'íslenska (Ísland)'),
	(314,N'it-CH',N'Italian (Switzerland)',N'italiano (Svizzera)'),
	(315,N'it-IT',N'Italian (Italy)',N'italiano (Italia)'),
	(316,N'it-SM',N'Italian (San Marino)',N'italiano (San Marino)'),
	(317,N'it-VA',N'Italian (Vatican City)',N'italiano (Città del Vaticano)'),
	(318,N'iu-Cans-CA',N'Inuktitut (Syllabics, Canada)',N'ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕᒥ)'),
	(319,N'iu-Latn-CA',N'Inuktitut (Latin, Canada)',N'Inuktitut (Kanatami)'),
	(320,N'ja-JP',N'Japanese (Japan)',N'日本語 (日本)'),
	(321,N'jgo-CM',N'Ngomba (Cameroon)',N'Ndaꞌa (Kamɛlûn)'),
	(322,N'jmc-TZ',N'Machame (Tanzania)',N'Kimachame (Tanzania)'),
	(323,N'jv-Java-ID',N'Javanese (Javanese, Indonesia)',N'ꦧꦱꦗꦮ (Indonesia)'),
	(324,N'jv-Latn-ID',N'Javanese (Indonesia)',N'Basa Jawa (Indonesia)'),
	(325,N'ka-GE',N'Georgian (Georgia)',N'ქართული (საქართველო)'),
	(326,N'kab-DZ',N'Kabyle (Algeria)',N'Taqbaylit (Lezzayer)'),
	(327,N'kam-KE',N'Kamba (Kenya)',N'Kikamba (Kenya)'),
	(328,N'kde-TZ',N'Makonde (Tanzania)',N'Chimakonde (Tanzania)'),
	(329,N'kea-CV',N'Kabuverdianu (Cabo Verde)',N'kabuverdianu (Kabu Verdi)'),
	(330,N'khq-ML',N'Koyra Chiini (Mali)',N'Koyra ciini (Maali)'),
	(331,N'ki-KE',N'Kikuyu (Kenya)',N'Gikuyu (Kenya)'),
	(332,N'kk-KZ',N'Kazakh (Kazakhstan)',N'қазақ тілі (Қазақстан)'),
	(333,N'kkj-CM',N'Kako (Cameroon)',N'kakɔ (Kamɛrun)'),
	(334,N'kl-GL',N'Greenlandic (Greenland)',N'kalaallisut (Kalaallit Nunaat)'),
	(335,N'kln-KE',N'Kalenjin (Kenya)',N'Kalenjin (Emetab Kenya)'),
	(336,N'km-KH',N'Khmer (Cambodia)',N'ភាសាខ្មែរ (កម្ពុជា)'),
	(337,N'kn-IN',N'Kannada (India)',N'ಕನ್ನಡ (ಭಾರತ)'),
	(338,N'ko-KP',N'Korean (North Korea)',N'한국어 (조선민주주의인민공화국)'),
	(339,N'ko-KR',N'Korean (Korea)',N'한국어(대한민국)'),
	(340,N'kok-IN',N'Konkani (India)',N'कोंकणी (भारत)'),
	(341,N'kr-NG',N'Kanuri (Nigeria)',N'Kanuri (Nigeria)'),
	(342,N'ks-Arab-IN',N'Kashmiri (Perso-Arabic)',N'کٲشُر (اَربی)'),
	(343,N'ks-Deva-IN',N'Kashmiri (Devanagari)',N'कॉशुर'),
	(344,N'ksb-TZ',N'Shambala (Tanzania)',N'Kishambaa (Tanzania)'),
	(345,N'ksf-CM',N'Bafia (Cameroon)',N'rikpa (kamɛrún)'),
	(346,N'ksh-DE',N'Colognian (Germany)',N'Kölsch (Doütschland)'),
	(347,N'ku-Arab-IQ',N'Central Kurdish (Iraq)',N'کوردیی ناوەڕاست (عێراق)'),
	(348,N'ku-Arab-IR',N'Kurdish (Perso-Arabic, Iran)',N'کوردی (ئێران)'),
	(349,N'kw-GB',N'Cornish (United Kingdom)',N'kernewek (Rywvaneth Unys)'),
	(350,N'ky-KG',N'Kyrgyz (Kyrgyzstan)',N'Кыргыз (Кыргызстан)'),
	(351,N'la-001',N'Latin (World)',N'lingua latīna (World)'),
	(352,N'lag-TZ',N'Langi (Tanzania)',N'Kɨlaangi (Taansanía)'),
	(353,N'lb-LU',N'Luxembourgish (Luxembourg)',N'Lëtzebuergesch (Lëtzebuerg)'),
	(354,N'lg-UG',N'Ganda (Uganda)',N'Luganda (Yuganda)'),
	(355,N'lkt-US',N'Lakota (United States)',N'Lakȟólʼiyapi (Mílahaŋska Tȟamákȟočhe)'),
	(356,N'ln-AO',N'Lingala (Angola)',N'lingála (Angóla)'),
	(357,N'ln-CD',N'Lingala (Congo DRC)',N'lingála (Republíki ya Kongó Demokratíki)'),
	(358,N'ln-CF',N'Lingala (Central African Republic)',N'lingála (Repibiki ya Afríka ya Káti)'),
	(359,N'ln-CG',N'Lingala (Congo)',N'lingála (Kongo)'),
	(360,N'lo-LA',N'Lao (Laos)',N'ລາວ (ລາວ)'),
	(361,N'lrc-IQ',N'Northern Luri (Iraq)',N'لۊری شومالی (Iraq)'),
	(362,N'lrc-IR',N'Northern Luri (Iran)',N'لۊری شومالی (Iran)'),
	(363,N'lt-LT',N'Lithuanian (Lithuania)',N'lietuvių (Lietuva)'),
	(364,N'lu-CD',N'Luba-Katanga (Congo DRC)',N'Tshiluba (Ditunga wa Kongu)'),
	(365,N'luo-KE',N'Luo (Kenya)',N'Dholuo (Kenya)'),
	(366,N'luy-KE',N'Luyia (Kenya)',N'Luluhia (Kenya)'),
	(367,N'lv-LV',N'Latvian (Latvia)',N'latviešu (Latvija)'),
	(368,N'mas-KE',N'Masai (Kenya)',N'Maa (Kenya)'),
	(369,N'mas-TZ',N'Masai (Tanzania)',N'Maa (Tansania)'),
	(370,N'mer-KE',N'Meru (Kenya)',N'Kĩmĩrũ (Kenya)'),
	(371,N'mfe-MU',N'Morisyen (Mauritius)',N'kreol morisien (Moris)'),
	(372,N'mg-MG',N'Malagasy (Madagascar)',N'Malagasy (Madagasikara)'),
	(373,N'mgh-MZ',N'Makhuwa-Meetto (Mozambique)',N'Makua (Umozambiki)'),
	(374,N'mgo-CM',N'Metaʼ (Cameroon)',N'metaʼ (Kamalun)'),
	(375,N'mi-NZ',N'Maori (New Zealand)',N'Reo Māori (Aotearoa)'),
	(376,N'mk-MK',N'Macedonian (Macedonia, FYRO)',N'македонски (Република Македонија)'),
	(377,N'ml-IN',N'Malayalam (India)',N'മലയാളം (ഇന്ത്യ)'),
	(378,N'mn-MN',N'Mongolian (Mongolia)',N'монгол (Монгол)'),
	(379,N'mn-Mong-CN',N'Mongolian (Traditional Mongolian, China)',N'ᠮᠣᠩᠭᠣᠤᠯ ᠬᠡᠯᠡ (ᠪᠦᠭᠦᠳᠡ ᠨᠠᠢᠷᠠᠮᠳᠠᠬᠤ ᠳᠤᠮᠳᠠᠳᠤ ᠠᠷᠠᠳ ᠣᠯᠣᠰ)'),
	(380,N'mn-Mong-MN',N'Mongolian (Traditional Mongolian, Mongolia)',N'ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ (ᠮᠣᠩᠭᠣᠯ ᠣᠯᠣᠰ)'),
	(381,N'mni-IN',N'Manipuri (India)',N'মৈতৈলোন্ (India)'),
	(382,N'moh-CA',N'Mohawk (Mohawk)',N'Kanien''kéha'),
	(383,N'mr-IN',N'Marathi (India)',N'मराठी (भारत)'),
	(384,N'ms-BN',N'Malay (Brunei)',N'Melayu (Brunei)'),
	(385,N'ms-MY',N'Malay (Malaysia)',N'Melayu (Malaysia)'),
	(386,N'ms-SG',N'Malay (Singapore)',N'Melayu (Singapura)'),
	(387,N'mt-MT',N'Maltese (Malta)',N'Malti (Malta)'),
	(388,N'mua-CM',N'Mundang (Cameroon)',N'MUNDAŊ (kameruŋ)'),
	(389,N'my-MM',N'Burmese (Myanmar)',N'မြန်မာ (မြန်မာ)'),
	(390,N'mzn-IR',N'Mazanderani (Iran)',N'مازرونی (ایران)'),
	(391,N'naq-NA',N'Nama (Namibia)',N'Khoekhoegowab (Namibiab)'),
	(392,N'nb-NO',N'Norwegian Bokmål (Norway)',N'norsk bokmål (Norge)'),
	(393,N'nb-SJ',N'Norwegian Bokmål (Svalbard and Jan Mayen)',N'norsk bokmål (Svalbard og Jan Mayen)'),
	(394,N'nd-ZW',N'North Ndebele (Zimbabwe)',N'isiNdebele (Zimbabwe)'),
	(395,N'nds-DE',N'Low German (Germany)',N'Neddersass’sch (Düütschland)'),
	(396,N'nds-NL',N'Low German (Netherlands)',N'Neddersass’sch (Nedderlannen)'),
	(397,N'ne-IN',N'Nepali (India)',N'नेपाली (भारत)'),
	(398,N'ne-NP',N'Nepali (Nepal)',N'नेपाली (नेपाल)'),
	(399,N'nl-AW',N'Dutch (Aruba)',N'Nederlands (Aruba)'),
	(400,N'nl-BE',N'Dutch (Belgium)',N'Nederlands (België)'),
	(401,N'nl-BQ',N'Dutch (Bonaire, Sint Eustatius and Saba)',N'Nederlands (Bonaire, Sint Eustatius en Saba)'),
	(402,N'nl-CW',N'Dutch (Curaçao)',N'Nederlands (Curaçao)'),
	(403,N'nl-NL',N'Dutch (Netherlands)',N'Nederlands (Nederland)'),
	(404,N'nl-SR',N'Dutch (Suriname)',N'Nederlands (Suriname)'),
	(405,N'nl-SX',N'Dutch (Sint Maarten)',N'Nederlands (Sint-Maarten)'),
	(406,N'nmg-CM',N'Kwasio (Cameroon)',N'Kwasio (Kamerun)'),
	(407,N'nn-NO',N'Norwegian Nynorsk (Norway)',N'nynorsk (Noreg)'),
	(408,N'nnh-CM',N'Ngiemboon (Cameroon)',N'Shwóŋò ngiembɔɔn (Kàmalûm)'),
	(409,N'nqo-GN',N'N''ko (Guinea)',N'ߒߞߏ (ߖߌ߬ߣߍ߬ ߞߊ߲ߓߍ߲)'),
	(410,N'nr-ZA',N'South Ndebele (South Africa)',N'isiNdebele (South Africa)'),
	(411,N'nso-ZA',N'Sesotho sa Leboa (South Africa)',N'Sesotho sa Leboa (Afrika Borwa)'),
	(412,N'nus-SS',N'Nuer (South Sudan)',N'Thok Nath (South Sudan)'),
	(413,N'nyn-UG',N'Nyankole (Uganda)',N'Runyankore (Uganda)'),
	(414,N'oc-FR',N'Occitan (France)',N'Occitan (França)'),
	(415,N'om-ET',N'Oromo (Ethiopia)',N'Oromoo (Itoophiyaa)'),
	(416,N'om-KE',N'Oromo (Kenya)',N'Oromoo (Keeniyaa)'),
	(417,N'or-IN',N'Odia (India)',N'ଓଡ଼ିଆ (ଭାରତ)'),
	(418,N'os-GE',N'Ossetic (Georgia)',N'ирон (Гуырдзыстон)'),
	(419,N'os-RU',N'Ossetic (Russia)',N'ирон (Уӕрӕсе)'),
	(420,N'pa-Arab-PK',N'Punjabi (Pakistan)',N'پنجابی (پاکستان)'),
	(421,N'pa-IN',N'Punjabi (India)',N'ਪੰਜਾਬੀ (ਭਾਰਤ)'),
	(422,N'pap-029',N'Papiamento (Caribbean)',N'Papiamentu (Caribbean)'),
	(423,N'pl-PL',N'Polish (Poland)',N'polski (Polska)'),
	(424,N'prg-001',N'Prussian (World)',N'prūsiskan (swītai)'),
	(425,N'prs-AF',N'Dari (Afghanistan)',N'درى (افغانستان)'),
	(426,N'ps-AF',N'Pashto (Afghanistan)',N'پښتو (افغانستان)'),
	(427,N'pt-AO',N'Portuguese (Angola)',N'português (Angola)'),
	(428,N'pt-BR',N'Portuguese (Brazil)',N'português (Brasil)'),
	(429,N'pt-CH',N'Portuguese (Switzerland)',N'português (Suíça)'),
	(430,N'pt-CV',N'Portuguese (Cabo Verde)',N'português (Cabo Verde)'),
	(431,N'pt-GQ',N'Portuguese (Equatorial Guinea)',N'português (Guiné Equatorial)'),
	(432,N'pt-GW',N'Portuguese (Guinea-Bissau)',N'português (Guiné-Bissau)'),
	(433,N'pt-LU',N'Portuguese (Luxembourg)',N'português (Luxemburgo)'),
	(434,N'pt-MO',N'Portuguese (Macao SAR)',N'português (RAE de Macau)'),
	(435,N'pt-MZ',N'Portuguese (Mozambique)',N'português (Moçambique)'),
	(436,N'pt-PT',N'Portuguese (Portugal)',N'português (Portugal)'),
	(437,N'pt-ST',N'Portuguese (São Tomé and Príncipe)',N'português (São Tomé e Príncipe)'),
	(438,N'pt-TL',N'Portuguese (Timor-Leste)',N'português (Timor-Leste)'),
	(439,N'quc-Latn-GT',N'K''iche'' (Guatemala)',N'K''iche'' (Guatemala)'),
	(440,N'quz-BO',N'Quechua (Bolivia)',N'Runasimi (Bolivia)'),
	(441,N'quz-EC',N'Quichua (Ecuador)',N'Runasimi (Ecuador)'),
	(442,N'quz-PE',N'Quechua (Peru)',N'Runasimi (Perú)'),
	(443,N'rm-CH',N'Romansh (Switzerland)',N'rumantsch (Svizra)'),
	(444,N'rn-BI',N'Rundi (Burundi)',N'Ikirundi (Uburundi)'),
	(445,N'ro-MD',N'Romanian (Moldova)',N'română (Republica Moldova)'),
	(446,N'ro-RO',N'Romanian (Romania)',N'română (România)'),
	(447,N'rof-TZ',N'Rombo (Tanzania)',N'Kihorombo (Tanzania)'),
	(448,N'ru-BY',N'Russian (Belarus)',N'русский (Беларусь)'),
	(449,N'ru-KG',N'Russian (Kyrgyzstan)',N'русский (Киргизия)'),
	(450,N'ru-KZ',N'Russian (Kazakhstan)',N'русский (Казахстан)'),
	(451,N'ru-MD',N'Russian (Moldova)',N'русский (Молдова)'),
	(452,N'ru-RU',N'Russian (Russia)',N'русский (Россия)'),
	(453,N'ru-UA',N'Russian (Ukraine)',N'русский (Украина)'),
	(454,N'rw-RW',N'Kinyarwanda (Rwanda)',N'Kinyarwanda (U Rwanda)'),
	(455,N'rwk-TZ',N'Rwa (Tanzania)',N'Kiruwa (Tanzania)'),
	(456,N'sa-IN',N'Sanskrit (India)',N'संस्कृत (भारतम्)'),
	(457,N'sah-RU',N'Sakha (Russia)',N'Саха (Россия)'),
	(458,N'saq-KE',N'Samburu (Kenya)',N'Kisampur (Kenya)'),
	(459,N'sbp-TZ',N'Sangu (Tanzania)',N'Ishisangu (Tansaniya)'),
	(460,N'sd-Arab-PK',N'Sindhi (Pakistan)',N'سنڌي (پاکستان)'),
	(461,N'sd-Deva-IN',N'Sindhi (Devanagari, India)',N'सिन्धी (India)'),
	(462,N'se-FI',N'Sami, Northern (Finland)',N'davvisámegiella (Suopma)'),
	(463,N'se-NO',N'Sami, Northern (Norway)',N'davvisámegiella (Norga)'),
	(464,N'se-SE',N'Sami, Northern (Sweden)',N'davvisámegiella (Ruoŧŧa)'),
	(465,N'seh-MZ',N'Sena (Mozambique)',N'sena (Moçambique)'),
	(466,N'ses-ML',N'Koyraboro Senni (Mali)',N'Koyraboro senni (Maali)'),
	(467,N'sg-CF',N'Sango (Central African Republic)',N'Sängö (Ködörösêse tî Bêafrîka)'),
	(468,N'shi-Latn-MA',N'Tachelhit (Latin, Morocco)',N'Tashelḥiyt (lmɣrib)'),
	(469,N'shi-Tfng-MA',N'Tachelhit (Tifinagh, Morocco)',N'ⵜⴰⵛⵍⵃⵉⵜ (ⵍⵎⵖⵔⵉⴱ)'),
	(470,N'si-LK',N'Sinhala (Sri Lanka)',N'සිංහල (ශ්‍රී ලංකාව)'),
	(471,N'sk-SK',N'Slovak (Slovakia)',N'slovenčina (Slovensko)'),
	(472,N'sl-SI',N'Slovenian (Slovenia)',N'slovenščina (Slovenija)'),
	(473,N'sma-NO',N'Sami, Southern (Norway)',N'åarjelsaemiengïele (Nöörje)'),
	(474,N'sma-SE',N'Sami, Southern (Sweden)',N'åarjelsaemiengïele (Sveerje)'),
	(475,N'smj-NO',N'Sami, Lule (Norway)',N'julevusámegiella (Vuodna)'),
	(476,N'smj-SE',N'Sami, Lule (Sweden)',N'julevusámegiella (Svierik)'),
	(477,N'smn-FI',N'Sami, Inari (Finland)',N'anarâškielâ (Suomâ)'),
	(478,N'sms-FI',N'Sami, Skolt (Finland)',N'sää´mǩiõll (Lää´ddjânnam)'),
	(479,N'sn-Latn-ZW',N'Shona (Latin, Zimbabwe)',N'chiShona (Zimbabwe)'),
	(480,N'so-DJ',N'Somali (Djibouti)',N'Soomaali (Jabuuti)'),
	(481,N'so-ET',N'Somali (Ethiopia)',N'Soomaali (Itoobiya)'),
	(482,N'so-KE',N'Somali (Kenya)',N'Soomaali (Kiiniya)'),
	(483,N'so-SO',N'Somali (Somalia)',N'Soomaali (Soomaaliya)'),
	(484,N'sq-AL',N'Albanian (Albania)',N'shqip (Shqipëri)'),
	(485,N'sq-MK',N'Albanian (Macedonia, FYRO)',N'shqip (Republika e Maqedonisë)'),
	(486,N'sq-XK',N'Albanian (Kosovo)',N'shqip (Kosovë)'),
	(487,N'sr-Cyrl-BA',N'Serbian (Cyrillic, Bosnia and Herzegovina)',N'српски (Босна и Херцеговина)'),
	(488,N'sr-Cyrl-ME',N'Serbian (Cyrillic, Montenegro)',N'српски (Црна Гора)'),
	(489,N'sr-Cyrl-RS',N'Serbian (Cyrillic, Serbia)',N'српски (Србија)'),
	(490,N'sr-Cyrl-XK',N'Serbian (Cyrillic, Kosovo)',N'српски (Косово)'),
	(491,N'sr-Latn-BA',N'Serbian (Latin, Bosnia and Herzegovina)',N'srpski (Bosna i Hercegovina)'),
	(492,N'sr-Latn-ME',N'Serbian (Latin, Montenegro)',N'srpski (Crna Gora)'),
	(493,N'sr-Latn-RS',N'Serbian (Latin, Serbia)',N'srpski (Srbija)'),
	(494,N'sr-Latn-XK',N'Serbian (Latin, Kosovo)',N'srpski (Kosovo)'),
	(495,N'ss-SZ',N'siSwati (Swaziland)',N'siSwati (Swaziland)'),
	(496,N'ss-ZA',N'siSwati (South Africa)',N'siSwati (South Africa)'),
	(497,N'ssy-ER',N'Saho (Eritrea)',N'Saho (Eretria)'),
	(498,N'st-LS',N'Sesotho (Lesotho)',N'Sesotho (Lesotho)'),
	(499,N'st-ZA',N'Sesotho (South Africa)',N'Sesotho (South Africa)'),
	(500,N'sv-AX',N'Swedish (Åland Islands)',N'svenska (Åland)'),
	(501,N'sv-FI',N'Swedish (Finland)',N'svenska (Finland)'),
	(502,N'sv-SE',N'Swedish (Sweden)',N'svenska (Sverige)'),
	(503,N'sw-CD',N'Kiswahili (Congo DRC)',N'Kiswahili (Jamhuri ya Kidemokrasia ya Kongo)'),
	(504,N'sw-KE',N'Kiswahili (Kenya)',N'Kiswahili (Kenya)'),
	(505,N'sw-TZ',N'Kiswahili (Tanzania)',N'Kiswahili (Tanzania)'),
	(506,N'sw-UG',N'Kiswahili (Uganda)',N'Kiswahili (Uganda)'),
	(507,N'syr-SY',N'Syriac (Syria)',N'ܣܘܪܝܝܐ (ܣܘܪܝܐ)'),
	(508,N'ta-IN',N'Tamil (India)',N'தமிழ் (இந்தியா)'),
	(509,N'ta-LK',N'Tamil (Sri Lanka)',N'தமிழ் (இலங்கை)'),
	(510,N'ta-MY',N'Tamil (Malaysia)',N'தமிழ் (மலேசியா)'),
	(511,N'ta-SG',N'Tamil (Singapore)',N'தமிழ் (சிங்கப்பூர்)'),
	(512,N'te-IN',N'Telugu (India)',N'తెలుగు (భారత దేశం)'),
	(513,N'teo-KE',N'Teso (Kenya)',N'Kiteso (Kenia)'),
	(514,N'teo-UG',N'Teso (Uganda)',N'Kiteso (Uganda)'),
	(515,N'tg-Cyrl-TJ',N'Tajik (Cyrillic, Tajikistan)',N'тоҷикӣ (Тоҷикистон)'),
	(516,N'th-TH',N'Thai (Thailand)',N'ไทย (ไทย)'),
	(517,N'ti-ER',N'Tigrinya (Eritrea)',N'ትግርኛ (ኤርትራ)'),
	(518,N'ti-ET',N'Tigrinya (Ethiopia)',N'ትግርኛ (ኢትዮጵያ)'),
	(519,N'tig-ER',N'Tigre (Eritrea)',N'ትግረ (ኤርትራ)'),
	(520,N'tk-TM',N'Turkmen (Turkmenistan)',N'Türkmen dili (Türkmenistan)'),
	(521,N'tn-BW',N'Setswana (Botswana)',N'Setswana (Botswana)'),
	(522,N'tn-ZA',N'Setswana (South Africa)',N'Setswana (Aforika Borwa)'),
	(523,N'to-TO',N'Tongan (Tonga)',N'lea fakatonga (Tonga)'),
	(524,N'tr-CY',N'Turkish (Cyprus)',N'Türkçe (Kıbrıs)'),
	(525,N'tr-TR',N'Turkish (Turkey)',N'Türkçe (Türkiye)'),
	(526,N'ts-ZA',N'Xitsonga (South Africa)',N'Xitsonga (South Africa)'),
	(527,N'tt-RU',N'Tatar (Russia)',N'Татар (Россия)'),
	(528,N'twq-NE',N'Tasawaq (Niger)',N'Tasawaq senni (Nižer)'),
	(529,N'tzm-Arab-MA',N'Central Atlas Tamazight (Arabic, Morocco)',N'أطلس المركزية التامازيتية (Morocco)'),
	(530,N'tzm-Latn-DZ',N'Central Atlas Tamazight (Latin, Algeria)',N'Tamaziɣt n laṭlaṣ (Djazaïr)'),
	(531,N'tzm-Latn-MA',N'Central Atlas Tamazight (Latin, Morocco)',N'Tamaziɣt n laṭlaṣ (Meṛṛuk)'),
	(532,N'tzm-Tfng-MA',N'Central Atlas Tamazight (Tifinagh, Morocco)',N'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⵎⵖⵔⵉⴱ)'),
	(533,N'ug-CN',N'Uyghur (China)',N'ئۇيغۇرچە (جۇڭخۇا خەلق جۇمھۇرىيىتى)'),
	(534,N'uk-UA',N'Ukrainian (Ukraine)',N'українська (Україна)'),
	(535,N'ur-IN',N'Urdu (India)',N'اردو (بھارت)'),
	(536,N'ur-PK',N'Urdu (Pakistan)',N'اُردو (پاکستان)'),
	(537,N'uz-Arab-AF',N'Uzbek (Perso-Arabic, Afghanistan)',N'اوزبیک (افغانستان)'),
	(538,N'uz-Cyrl-UZ',N'Uzbek (Cyrillic, Uzbekistan)',N'ўзбекча (Ўзбекистон)'),
	(539,N'uz-Latn-UZ',N'Uzbek (Latin, Uzbekistan)',N'o‘zbek (Oʻzbekiston)'),
	(540,N'vai-Latn-LR',N'Vai (Latin, Liberia)',N'Vai (Laibhiya)'),
	(541,N'vai-Vaii-LR',N'Vai (Vai, Liberia)',N'ꕙꔤ (ꕞꔤꔫꕩ)'),
	(542,N've-ZA',N'Venda (South Africa)',N'Tshivenḓa (South Africa)'),
	(543,N'vi-VN',N'Vietnamese (Vietnam)',N'Tiếng Việt (Việt Nam)'),
	(544,N'vo-001',N'Volapük (World)',N'Volapük (World)'),
	(545,N'vun-TZ',N'Vunjo (Tanzania)',N'Kyivunjo (Tanzania)'),
	(546,N'wae-CH',N'Walser (Switzerland)',N'Walser (Schwiz)'),
	(547,N'wal-ET',N'Wolaytta (Ethiopia)',N'ወላይታቱ (ኢትዮጵያ)'),
	(548,N'wo-SN',N'Wolof (Senegal)',N'Wolof (Senegaal)'),
	(549,N'xh-ZA',N'isiXhosa (South Africa)',N'isiXhosa (eMzantsi Afrika)'),
	(550,N'xog-UG',N'Soga (Uganda)',N'Olusoga (Yuganda)'),
	(551,N'yav-CM',N'Yangben (Cameroon)',N'nuasue (Kemelún)'),
	(552,N'yi-001',N'Yiddish (World)',N'ייִדיש (וועלט)'),
	(553,N'yo-BJ',N'Yoruba (Benin)',N'Èdè Yorùbá (Orílɛ́ède Bɛ̀nɛ̀)'),
	(554,N'yo-NG',N'Yoruba (Nigeria)',N'Èdè Yorùbá (Orílẹ́ède Nàìjíríà)'),
	(555,N'zgh-Tfng-MA',N'Standard Moroccan Tamazight (Tifinagh, Morocco)',N'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⵎⵖⵔⵉⴱ)'),
	(556,N'zh-CN',N'Chinese (Simplified, China)',N'中文(中国)'),
	(557,N'zh-Hans-HK',N'Chinese (Simplified Han, Hong Kong SAR)',N'中文 (香港特别行政区)'),
	(558,N'zh-Hans-MO',N'Chinese (Simplified Han, Macao SAR)',N'中文 (澳门特别行政区)'),
	(559,N'zh-HK',N'Chinese (Traditional, Hong Kong SAR)',N'中文(香港特別行政區)'),
	(560,N'zh-MO',N'Chinese (Traditional, Macao SAR)',N'中文(澳門特別行政區)'),
	(561,N'zh-SG',N'Chinese (Simplified, Singapore)',N'中文(新加坡)'),
	(562,N'zh-TW',N'Chinese (Traditional, Taiwan)',N'中文(台灣)'),
	(563,N'zu-ZA',N'isiZulu (South Africa)',N'isiZulu (iNingizimu Afrika)')
	
SET IDENTITY_INSERT [dbo].[Culture] OFF
